// Catégories de commerce avec labels, icônes et couleurs - 118 catégories par ordre alphabétique
export const BUSINESS_CATEGORIES = {
  accessoires: { label: 'Accessoires', shortLabel: 'Accessoires', icon: '🎒', accentColor: '#14B8A6' },
  agence_voyage: { label: 'Agence de voyage', shortLabel: 'Voyages', icon: '✈️', accentColor: '#0EA5E9' },
  animalerie: { label: 'Animalerie', shortLabel: 'Animaleries', icon: '🐕', accentColor: '#F59E0B' },
  art_table: { label: 'Arts de la table', shortLabel: 'Arts table', icon: '🍽️', accentColor: '#EC4899' },
  arts_martiaux: { label: 'Arts martiaux', shortLabel: 'Arts martiaux', icon: '🥋', accentColor: '#1E293B' },
  assurance: { label: 'Assurance', shortLabel: 'Assurances', icon: '🛡️', accentColor: '#0891B2' },
  audioprothésiste: { label: 'Audioprothésiste', shortLabel: 'Audioprothèses', icon: '👂', accentColor: '#8B5CF6' },
  auto_école: { label: 'Auto-école', shortLabel: 'Auto-écoles', icon: '🚦', accentColor: '#F97316' },
  banque: { label: 'Banque', shortLabel: 'Banques', icon: '🏦', accentColor: '#1E40AF' },
  bar: { label: 'Bar', shortLabel: 'Bars', icon: '🍺', accentColor: '#F59E0B' },
  barbier: { label: 'Barbier', shortLabel: 'Barbiers', icon: '💈', accentColor: '#3B82F6' },
  bazaar: { label: 'Bazar', shortLabel: 'Bazars', icon: '🎁', accentColor: '#A855F7' },
  bijouterie: { label: 'Bijouterie', shortLabel: 'Bijouteries', icon: '💍', accentColor: '#FCD34D' },
  boucherie: { label: 'Boucherie', shortLabel: 'Boucheries', icon: '🥩', accentColor: '#991B1B' },
  boulangerie: { label: 'Boulangerie', shortLabel: 'Boulangeries', icon: '🥐', accentColor: '#D4A574' },
  boutique_cadeau: { label: 'Boutique cadeaux', shortLabel: 'Cadeaux', icon: '🎀', accentColor: '#EC4899' },
  bowling: { label: 'Bowling', shortLabel: 'Bowlings', icon: '🎳', accentColor: '#3B82F6' },
  boxe: { label: 'Boxe', shortLabel: 'Boxe', icon: '🥊', accentColor: '#EF4444' },
  bricolage: { label: 'Bricolage', shortLabel: 'Bricolage', icon: '🔨', accentColor: '#F97316' },
  café: { label: 'Café', shortLabel: 'Cafés', icon: '☕', accentColor: '#8B4513' },
  carwash: { label: 'Lavage auto', shortLabel: 'Lavages', icon: '🚿', accentColor: '#0EA5E9' },
  caviste: { label: 'Caviste', shortLabel: 'Cavistes', icon: '🍷', accentColor: '#7C2D12' },
  chaussures: { label: 'Chaussures', shortLabel: 'Chaussures', icon: '👟', accentColor: '#F97316' },
  cinéma: { label: 'Cinéma', shortLabel: 'Cinémas', icon: '🎬', accentColor: '#DC2626' },
  coiffeur: { label: 'Salon de coiffure', shortLabel: 'Coiffeurs', icon: '✂️', accentColor: '#E879F9' },
  commerce: { label: 'Commerce général', shortLabel: 'Commerces', icon: '🏪', accentColor: '#0000ff' },
  cordonnerie: { label: 'Cordonnerie', shortLabel: 'Cordonneries', icon: '👞', accentColor: '#78716C' },
  cosmétiques: { label: 'Cosmétiques', shortLabel: 'Cosmétiques', icon: '💄', accentColor: '#F43F5E' },
  crèche: { label: 'Crèche', shortLabel: 'Crèches', icon: '👶', accentColor: '#EC4899' },
  cuisine_équipée: { label: 'Cuisine équipée', shortLabel: 'Cuisines', icon: '🍳', accentColor: '#EF4444' },
  danse: { label: 'École de danse', shortLabel: 'Danse', icon: '💃', accentColor: '#EC4899' },
  décoration: { label: 'Décoration', shortLabel: 'Décorations', icon: '🛋️', accentColor: '#A78BFA' },
  diététicien: { label: 'Diététicien', shortLabel: 'Diététiciens', icon: '🥗', accentColor: '#84CC16' },
  disquaire: { label: 'Disquaire', shortLabel: 'Disquaires', icon: '🎵', accentColor: '#1E293B' },
  droguerie: { label: 'Droguerie', shortLabel: 'Drogueries', icon: '🧴', accentColor: '#06B6D4' },
  drones: { label: 'Drones', shortLabel: 'Drones', icon: '🚁', accentColor: '#64748B' },
  école_langue: { label: 'École de langue', shortLabel: 'Langues', icon: '🗣️', accentColor: '#06B6D4' },
  école_musique: { label: 'École de musique', shortLabel: 'Musique', icon: '🎹', accentColor: '#8B5CF6' },
  électroménager: { label: 'Électroménager', shortLabel: 'Électroménager', icon: '🔌', accentColor: '#6366F1' },
  épicerie: { label: 'Épicerie fine', shortLabel: 'Épiceries', icon: '🏺', accentColor: '#A78BFA' },
  épicerie_bio: { label: 'Épicerie bio', shortLabel: 'Épiceries bio', icon: '🥬', accentColor: '#22C55E' },
  escalade: { label: 'Escalade', shortLabel: 'Escalade', icon: '🧗', accentColor: '#F97316' },
  escape_game: { label: 'Escape game', shortLabel: 'Escape games', icon: '🔐', accentColor: '#F97316' },
  esthétique: { label: 'Esthétique', shortLabel: 'Esthétique', icon: '✨', accentColor: '#F59E0B' },
  fastfood: { label: 'Fast-food', shortLabel: 'Fast-foods', icon: '🍔', accentColor: '#DC2626' },
  fleuriste: { label: 'Fleuriste', shortLabel: 'Fleuristes', icon: '🌸', accentColor: '#00A699' },
  formation_pro: { label: 'Formation pro', shortLabel: 'Formations', icon: '🎓', accentColor: '#3B82F6' },
  fromagerie: { label: 'Fromagerie', shortLabel: 'Fromageries', icon: '🧀', accentColor: '#FCD34D' },
  garage: { label: 'Garage/Automobile', shortLabel: 'Garages', icon: '🚗', accentColor: '#6B7280' },
  glacier: { label: 'Glacier', shortLabel: 'Glaciers', icon: '🍦', accentColor: '#38BDF8' },
  horlogerie: { label: 'Horlogerie', shortLabel: 'Horlogeries', icon: '⌚', accentColor: '#1E293B' },
  hôtel: { label: 'Hôtel', shortLabel: 'Hôtels', icon: '🏨', accentColor: '#3B82F6' },
  impression_3d: { label: 'Impression 3D', shortLabel: 'Impression 3D', icon: '🖨️', accentColor: '#A855F7' },
  informatique: { label: 'Informatique', shortLabel: 'Informatique', icon: '💻', accentColor: '#3B82F6' },
  institut_beauté: { label: 'Institut de beauté', shortLabel: 'Instituts', icon: '💅', accentColor: '#F472B6' },
  jardinerie: { label: 'Jardinerie', shortLabel: 'Jardineries', icon: '🌱', accentColor: '#22C55E' },
  jeux_vidéo: { label: 'Jeux vidéo', shortLabel: 'Gaming', icon: '🎮', accentColor: '#8B5CF6' },
  jouets: { label: 'Jouets', shortLabel: 'Jouets', icon: '🧸', accentColor: '#EC4899' },
  karting: { label: 'Karting', shortLabel: 'Kartings', icon: '🏎️', accentColor: '#EF4444' },
  kinésithérapeute: { label: 'Kinésithérapeute', shortLabel: 'Kinés', icon: '🤲', accentColor: '#06B6D4' },
  laser_game: { label: 'Laser game', shortLabel: 'Laser games', icon: '🔫', accentColor: '#EF4444' },
  librairie: { label: 'Librairie', shortLabel: 'Librairies', icon: '📚', accentColor: '#7C3AED' },
  lingerie: { label: 'Lingerie', shortLabel: 'Lingeries', icon: '👙', accentColor: '#F472B6' },
  literie: { label: 'Literie', shortLabel: 'Literies', icon: '🛏️', accentColor: '#0EA5E9' },
  location_matériel: { label: 'Location matériel', shortLabel: 'Locations', icon: '🎪', accentColor: '#A855F7' },
  luminaires: { label: 'Luminaires', shortLabel: 'Luminaires', icon: '💡', accentColor: '#FCD34D' },
  magasin_sport: { label: 'Magasin de sport', shortLabel: 'Sports', icon: '⚽', accentColor: '#10B981' },
  magasin_vrac: { label: 'Magasin vrac', shortLabel: 'Magasins vrac', icon: '♻️', accentColor: '#059669' },
  maroquinerie: { label: 'Maroquinerie', shortLabel: 'Maroquineries', icon: '👜', accentColor: '#78716C' },
  marché: { label: 'Marché', shortLabel: 'Marchés', icon: '🧺', accentColor: '#F59E0B' },
  massage: { label: 'Massage', shortLabel: 'Massages', icon: '💆', accentColor: '#8B5CF6' },
  mercerie: { label: 'Mercerie', shortLabel: 'Merceries', icon: '🧵', accentColor: '#A855F7' },
  meubles: { label: 'Meubles', shortLabel: 'Meubles', icon: '🪑', accentColor: '#78716C' },
  mode_seconde_main: { label: 'Friperie', shortLabel: 'Friperies', icon: '♻️', accentColor: '#059669' },
  musée: { label: 'Musée', shortLabel: 'Musées', icon: '🏛️', accentColor: '#64748B' },
  onglerie: { label: 'Onglerie', shortLabel: 'Ongleries', icon: '💅', accentColor: '#EC4899' },
  opticien: { label: 'Opticien', shortLabel: 'Opticiens', icon: '👓', accentColor: '#3B82F6' },
  ostéopathe: { label: 'Ostéopathe', shortLabel: 'Ostéopathes', icon: '🦴', accentColor: '#22C55E' },
  paintball: { label: 'Paintball', shortLabel: 'Paintballs', icon: '🎯', accentColor: '#22C55E' },
  papeterie: { label: 'Papeterie', shortLabel: 'Papeteries', icon: '✏️', accentColor: '#F59E0B' },
  parc_attraction: { label: 'Parc d\'attraction', shortLabel: 'Parcs', icon: '🎢', accentColor: '#DC2626' },
  parfumerie: { label: 'Parfumerie', shortLabel: 'Parfumeries', icon: '🌺', accentColor: '#C026D3' },
  pâtisserie: { label: 'Pâtisserie', shortLabel: 'Pâtisseries', icon: '🧁', accentColor: '#F472B6' },
  paysagiste: { label: 'Paysagiste', shortLabel: 'Paysagistes', icon: '🌳', accentColor: '#059669' },
  pension_animaux: { label: 'Pension animaux', shortLabel: 'Pensions', icon: '🏠', accentColor: '#06B6D4' },
  percings: { label: 'Piercings', shortLabel: 'Piercings', icon: '💎', accentColor: '#6366F1' },
  pharmacie: { label: 'Pharmacie', shortLabel: 'Pharmacies', icon: '💊', accentColor: '#0EA5E9' },
  photographe: { label: 'Photographe', shortLabel: 'Photographes', icon: '📸', accentColor: '#F59E0B' },
  photo_vidéo: { label: 'Photo/Vidéo', shortLabel: 'Photo', icon: '📷', accentColor: '#F59E0B' },
  piscine: { label: 'Piscine', shortLabel: 'Piscines', icon: '🏊', accentColor: '#0EA5E9' },
  pizzeria: { label: 'Pizzeria', shortLabel: 'Pizzerias', icon: '🍕', accentColor: '#FF6B35' },
  pneus: { label: 'Centre pneus', shortLabel: 'Pneus', icon: '🛞', accentColor: '#1E293B' },
  poissonerie: { label: 'Poissonnerie', shortLabel: 'Poissonneries', icon: '🐟', accentColor: '#0EA5E9' },
  pressing: { label: 'Pressing', shortLabel: 'Pressings', icon: '👔', accentColor: '#06B6D4' },
  primeur: { label: 'Primeur', shortLabel: 'Primeurs', icon: '🍎', accentColor: '#EF4444' },
  réparation_téléphone: { label: 'Réparation téléphone', shortLabel: 'Réparation', icon: '🔧', accentColor: '#06B6D4' },
  restaurant: { label: 'Restaurant', shortLabel: 'Restaurants', icon: '🍽️', accentColor: '#0000ff' },
  salle_fêtes: { label: 'Salle des fêtes', shortLabel: 'Salles fêtes', icon: '🎉', accentColor: '#F59E0B' },
  salle_sport: { label: 'Salle de sport', shortLabel: 'Salles de sport', icon: '💪', accentColor: '#DC2626' },
  sauna: { label: 'Sauna/Hammam', shortLabel: 'Saunas', icon: '🧘', accentColor: '#FB923C' },
  serrurerie: { label: 'Serrurerie', shortLabel: 'Serrureries', icon: '🔑', accentColor: '#64748B' },
  soutien_scolaire: { label: 'Soutien scolaire', shortLabel: 'Soutien', icon: '📝', accentColor: '#F59E0B' },
  spa: { label: 'Spa', shortLabel: 'Spas', icon: '🧖', accentColor: '#06B6D4' },
  station_service: { label: 'Station service', shortLabel: 'Stations', icon: '⛽', accentColor: '#DC2626' },
  supermarché: { label: 'Supermarché', shortLabel: 'Supermarchés', icon: '🛒', accentColor: '#10B981' },
  tabac_presse: { label: 'Tabac/Presse', shortLabel: 'Tabacs', icon: '📰', accentColor: '#78716C' },
  tatouage: { label: 'Tatouage', shortLabel: 'Tatouages', icon: '🖋️', accentColor: '#1E293B' },
  tea: { label: 'Salon de thé', shortLabel: 'Salons de thé', icon: '🍵', accentColor: '#84CC16' },
  téléphonie: { label: 'Téléphonie', shortLabel: 'Téléphones', icon: '📱', accentColor: '#1E293B' },
  théâtre: { label: 'Théâtre', shortLabel: 'Théâtres', icon: '🎭', accentColor: '#A855F7' },
  toilettage: { label: 'Toilettage', shortLabel: 'Toilettages', icon: '🐩', accentColor: '#EC4899' },
  traiteur: { label: 'Traiteur', shortLabel: 'Traiteurs', icon: '🥘', accentColor: '#F97316' },
  traiteur_événementiel: { label: 'Traiteur événementiel', shortLabel: 'Événementiel', icon: '🎊', accentColor: '#EC4899' },
  vélo: { label: 'Magasin vélo', shortLabel: 'Vélos', icon: '🚴', accentColor: '#84CC16' },
  vêtements: { label: 'Mode & Vêtements', shortLabel: 'Vêtements', icon: '👕', accentColor: '#EC4899' },
  vêtements_enfant: { label: 'Vêtements enfant', shortLabel: 'Enfants', icon: '👶', accentColor: '#38BDF8' },
  vétérinaire: { label: 'Vétérinaire', shortLabel: 'Vétérinaires', icon: '🐾', accentColor: '#10B981' },
  yoga: { label: 'Yoga', shortLabel: 'Yoga', icon: '🧘', accentColor: '#8B5CF6' }
} as const;

// Array pour les sélecteurs - 118 catégories par ordre alphabétique
export const CATEGORY_OPTIONS = [
  { key: 'accessoires', label: BUSINESS_CATEGORIES.accessoires.label, icon: BUSINESS_CATEGORIES.accessoires.icon },
  { key: 'agence_voyage', label: BUSINESS_CATEGORIES.agence_voyage.label, icon: BUSINESS_CATEGORIES.agence_voyage.icon },
  { key: 'animalerie', label: BUSINESS_CATEGORIES.animalerie.label, icon: BUSINESS_CATEGORIES.animalerie.icon },
  { key: 'art_table', label: BUSINESS_CATEGORIES.art_table.label, icon: BUSINESS_CATEGORIES.art_table.icon },
  { key: 'arts_martiaux', label: BUSINESS_CATEGORIES.arts_martiaux.label, icon: BUSINESS_CATEGORIES.arts_martiaux.icon },
  { key: 'assurance', label: BUSINESS_CATEGORIES.assurance.label, icon: BUSINESS_CATEGORIES.assurance.icon },
  { key: 'audioprothésiste', label: BUSINESS_CATEGORIES.audioprothésiste.label, icon: BUSINESS_CATEGORIES.audioprothésiste.icon },
  { key: 'auto_école', label: BUSINESS_CATEGORIES.auto_école.label, icon: BUSINESS_CATEGORIES.auto_école.icon },
  { key: 'banque', label: BUSINESS_CATEGORIES.banque.label, icon: BUSINESS_CATEGORIES.banque.icon },
  { key: 'bar', label: BUSINESS_CATEGORIES.bar.label, icon: BUSINESS_CATEGORIES.bar.icon },
  { key: 'barbier', label: BUSINESS_CATEGORIES.barbier.label, icon: BUSINESS_CATEGORIES.barbier.icon },
  { key: 'bazaar', label: BUSINESS_CATEGORIES.bazaar.label, icon: BUSINESS_CATEGORIES.bazaar.icon },
  { key: 'bijouterie', label: BUSINESS_CATEGORIES.bijouterie.label, icon: BUSINESS_CATEGORIES.bijouterie.icon },
  { key: 'boucherie', label: BUSINESS_CATEGORIES.boucherie.label, icon: BUSINESS_CATEGORIES.boucherie.icon },
  { key: 'boulangerie', label: BUSINESS_CATEGORIES.boulangerie.label, icon: BUSINESS_CATEGORIES.boulangerie.icon },
  { key: 'boutique_cadeau', label: BUSINESS_CATEGORIES.boutique_cadeau.label, icon: BUSINESS_CATEGORIES.boutique_cadeau.icon },
  { key: 'bowling', label: BUSINESS_CATEGORIES.bowling.label, icon: BUSINESS_CATEGORIES.bowling.icon },
  { key: 'boxe', label: BUSINESS_CATEGORIES.boxe.label, icon: BUSINESS_CATEGORIES.boxe.icon },
  { key: 'bricolage', label: BUSINESS_CATEGORIES.bricolage.label, icon: BUSINESS_CATEGORIES.bricolage.icon },
  { key: 'café', label: BUSINESS_CATEGORIES.café.label, icon: BUSINESS_CATEGORIES.café.icon },
  { key: 'carwash', label: BUSINESS_CATEGORIES.carwash.label, icon: BUSINESS_CATEGORIES.carwash.icon },
  { key: 'caviste', label: BUSINESS_CATEGORIES.caviste.label, icon: BUSINESS_CATEGORIES.caviste.icon },
  { key: 'chaussures', label: BUSINESS_CATEGORIES.chaussures.label, icon: BUSINESS_CATEGORIES.chaussures.icon },
  { key: 'cinéma', label: BUSINESS_CATEGORIES.cinéma.label, icon: BUSINESS_CATEGORIES.cinéma.icon },
  { key: 'coiffeur', label: BUSINESS_CATEGORIES.coiffeur.label, icon: BUSINESS_CATEGORIES.coiffeur.icon },
  { key: 'commerce', label: BUSINESS_CATEGORIES.commerce.label, icon: BUSINESS_CATEGORIES.commerce.icon },
  { key: 'cordonnerie', label: BUSINESS_CATEGORIES.cordonnerie.label, icon: BUSINESS_CATEGORIES.cordonnerie.icon },
  { key: 'cosmétiques', label: BUSINESS_CATEGORIES.cosmétiques.label, icon: BUSINESS_CATEGORIES.cosmétiques.icon },
  { key: 'crèche', label: BUSINESS_CATEGORIES.crèche.label, icon: BUSINESS_CATEGORIES.crèche.icon },
  { key: 'cuisine_équipée', label: BUSINESS_CATEGORIES.cuisine_équipée.label, icon: BUSINESS_CATEGORIES.cuisine_équipée.icon },
  { key: 'danse', label: BUSINESS_CATEGORIES.danse.label, icon: BUSINESS_CATEGORIES.danse.icon },
  { key: 'décoration', label: BUSINESS_CATEGORIES.décoration.label, icon: BUSINESS_CATEGORIES.décoration.icon },
  { key: 'diététicien', label: BUSINESS_CATEGORIES.diététicien.label, icon: BUSINESS_CATEGORIES.diététicien.icon },
  { key: 'disquaire', label: BUSINESS_CATEGORIES.disquaire.label, icon: BUSINESS_CATEGORIES.disquaire.icon },
  { key: 'droguerie', label: BUSINESS_CATEGORIES.droguerie.label, icon: BUSINESS_CATEGORIES.droguerie.icon },
  { key: 'drones', label: BUSINESS_CATEGORIES.drones.label, icon: BUSINESS_CATEGORIES.drones.icon },
  { key: 'école_langue', label: BUSINESS_CATEGORIES.école_langue.label, icon: BUSINESS_CATEGORIES.école_langue.icon },
  { key: 'école_musique', label: BUSINESS_CATEGORIES.école_musique.label, icon: BUSINESS_CATEGORIES.école_musique.icon },
  { key: 'électroménager', label: BUSINESS_CATEGORIES.électroménager.label, icon: BUSINESS_CATEGORIES.électroménager.icon },
  { key: 'épicerie', label: BUSINESS_CATEGORIES.épicerie.label, icon: BUSINESS_CATEGORIES.épicerie.icon },
  { key: 'épicerie_bio', label: BUSINESS_CATEGORIES.épicerie_bio.label, icon: BUSINESS_CATEGORIES.épicerie_bio.icon },
  { key: 'escalade', label: BUSINESS_CATEGORIES.escalade.label, icon: BUSINESS_CATEGORIES.escalade.icon },
  { key: 'escape_game', label: BUSINESS_CATEGORIES.escape_game.label, icon: BUSINESS_CATEGORIES.escape_game.icon },
  { key: 'esthétique', label: BUSINESS_CATEGORIES.esthétique.label, icon: BUSINESS_CATEGORIES.esthétique.icon },
  { key: 'fastfood', label: BUSINESS_CATEGORIES.fastfood.label, icon: BUSINESS_CATEGORIES.fastfood.icon },
  { key: 'fleuriste', label: BUSINESS_CATEGORIES.fleuriste.label, icon: BUSINESS_CATEGORIES.fleuriste.icon },
  { key: 'formation_pro', label: BUSINESS_CATEGORIES.formation_pro.label, icon: BUSINESS_CATEGORIES.formation_pro.icon },
  { key: 'fromagerie', label: BUSINESS_CATEGORIES.fromagerie.label, icon: BUSINESS_CATEGORIES.fromagerie.icon },
  { key: 'garage', label: BUSINESS_CATEGORIES.garage.label, icon: BUSINESS_CATEGORIES.garage.icon },
  { key: 'glacier', label: BUSINESS_CATEGORIES.glacier.label, icon: BUSINESS_CATEGORIES.glacier.icon },
  { key: 'horlogerie', label: BUSINESS_CATEGORIES.horlogerie.label, icon: BUSINESS_CATEGORIES.horlogerie.icon },
  { key: 'hôtel', label: BUSINESS_CATEGORIES.hôtel.label, icon: BUSINESS_CATEGORIES.hôtel.icon },
  { key: 'impression_3d', label: BUSINESS_CATEGORIES.impression_3d.label, icon: BUSINESS_CATEGORIES.impression_3d.icon },
  { key: 'informatique', label: BUSINESS_CATEGORIES.informatique.label, icon: BUSINESS_CATEGORIES.informatique.icon },
  { key: 'institut_beauté', label: BUSINESS_CATEGORIES.institut_beauté.label, icon: BUSINESS_CATEGORIES.institut_beauté.icon },
  { key: 'jardinerie', label: BUSINESS_CATEGORIES.jardinerie.label, icon: BUSINESS_CATEGORIES.jardinerie.icon },
  { key: 'jeux_vidéo', label: BUSINESS_CATEGORIES.jeux_vidéo.label, icon: BUSINESS_CATEGORIES.jeux_vidéo.icon },
  { key: 'jouets', label: BUSINESS_CATEGORIES.jouets.label, icon: BUSINESS_CATEGORIES.jouets.icon },
  { key: 'karting', label: BUSINESS_CATEGORIES.karting.label, icon: BUSINESS_CATEGORIES.karting.icon },
  { key: 'kinésithérapeute', label: BUSINESS_CATEGORIES.kinésithérapeute.label, icon: BUSINESS_CATEGORIES.kinésithérapeute.icon },
  { key: 'laser_game', label: BUSINESS_CATEGORIES.laser_game.label, icon: BUSINESS_CATEGORIES.laser_game.icon },
  { key: 'librairie', label: BUSINESS_CATEGORIES.librairie.label, icon: BUSINESS_CATEGORIES.librairie.icon },
  { key: 'lingerie', label: BUSINESS_CATEGORIES.lingerie.label, icon: BUSINESS_CATEGORIES.lingerie.icon },
  { key: 'literie', label: BUSINESS_CATEGORIES.literie.label, icon: BUSINESS_CATEGORIES.literie.icon },
  { key: 'location_matériel', label: BUSINESS_CATEGORIES.location_matériel.label, icon: BUSINESS_CATEGORIES.location_matériel.icon },
  { key: 'luminaires', label: BUSINESS_CATEGORIES.luminaires.label, icon: BUSINESS_CATEGORIES.luminaires.icon },
  { key: 'magasin_sport', label: BUSINESS_CATEGORIES.magasin_sport.label, icon: BUSINESS_CATEGORIES.magasin_sport.icon },
  { key: 'magasin_vrac', label: BUSINESS_CATEGORIES.magasin_vrac.label, icon: BUSINESS_CATEGORIES.magasin_vrac.icon },
  { key: 'maroquinerie', label: BUSINESS_CATEGORIES.maroquinerie.label, icon: BUSINESS_CATEGORIES.maroquinerie.icon },
  { key: 'marché', label: BUSINESS_CATEGORIES.marché.label, icon: BUSINESS_CATEGORIES.marché.icon },
  { key: 'massage', label: BUSINESS_CATEGORIES.massage.label, icon: BUSINESS_CATEGORIES.massage.icon },
  { key: 'mercerie', label: BUSINESS_CATEGORIES.mercerie.label, icon: BUSINESS_CATEGORIES.mercerie.icon },
  { key: 'meubles', label: BUSINESS_CATEGORIES.meubles.label, icon: BUSINESS_CATEGORIES.meubles.icon },
  { key: 'mode_seconde_main', label: BUSINESS_CATEGORIES.mode_seconde_main.label, icon: BUSINESS_CATEGORIES.mode_seconde_main.icon },
  { key: 'musée', label: BUSINESS_CATEGORIES.musée.label, icon: BUSINESS_CATEGORIES.musée.icon },
  { key: 'onglerie', label: BUSINESS_CATEGORIES.onglerie.label, icon: BUSINESS_CATEGORIES.onglerie.icon },
  { key: 'opticien', label: BUSINESS_CATEGORIES.opticien.label, icon: BUSINESS_CATEGORIES.opticien.icon },
  { key: 'ostéopathe', label: BUSINESS_CATEGORIES.ostéopathe.label, icon: BUSINESS_CATEGORIES.ostéopathe.icon },
  { key: 'paintball', label: BUSINESS_CATEGORIES.paintball.label, icon: BUSINESS_CATEGORIES.paintball.icon },
  { key: 'papeterie', label: BUSINESS_CATEGORIES.papeterie.label, icon: BUSINESS_CATEGORIES.papeterie.icon },
  { key: 'parc_attraction', label: BUSINESS_CATEGORIES.parc_attraction.label, icon: BUSINESS_CATEGORIES.parc_attraction.icon },
  { key: 'parfumerie', label: BUSINESS_CATEGORIES.parfumerie.label, icon: BUSINESS_CATEGORIES.parfumerie.icon },
  { key: 'pâtisserie', label: BUSINESS_CATEGORIES.pâtisserie.label, icon: BUSINESS_CATEGORIES.pâtisserie.icon },
  { key: 'paysagiste', label: BUSINESS_CATEGORIES.paysagiste.label, icon: BUSINESS_CATEGORIES.paysagiste.icon },
  { key: 'pension_animaux', label: BUSINESS_CATEGORIES.pension_animaux.label, icon: BUSINESS_CATEGORIES.pension_animaux.icon },
  { key: 'percings', label: BUSINESS_CATEGORIES.percings.label, icon: BUSINESS_CATEGORIES.percings.icon },
  { key: 'pharmacie', label: BUSINESS_CATEGORIES.pharmacie.label, icon: BUSINESS_CATEGORIES.pharmacie.icon },
  { key: 'photographe', label: BUSINESS_CATEGORIES.photographe.label, icon: BUSINESS_CATEGORIES.photographe.icon },
  { key: 'photo_vidéo', label: BUSINESS_CATEGORIES.photo_vidéo.label, icon: BUSINESS_CATEGORIES.photo_vidéo.icon },
  { key: 'piscine', label: BUSINESS_CATEGORIES.piscine.label, icon: BUSINESS_CATEGORIES.piscine.icon },
  { key: 'pizzeria', label: BUSINESS_CATEGORIES.pizzeria.label, icon: BUSINESS_CATEGORIES.pizzeria.icon },
  { key: 'pneus', label: BUSINESS_CATEGORIES.pneus.label, icon: BUSINESS_CATEGORIES.pneus.icon },
  { key: 'poissonerie', label: BUSINESS_CATEGORIES.poissonerie.label, icon: BUSINESS_CATEGORIES.poissonerie.icon },
  { key: 'pressing', label: BUSINESS_CATEGORIES.pressing.label, icon: BUSINESS_CATEGORIES.pressing.icon },
  { key: 'primeur', label: BUSINESS_CATEGORIES.primeur.label, icon: BUSINESS_CATEGORIES.primeur.icon },
  { key: 'réparation_téléphone', label: BUSINESS_CATEGORIES.réparation_téléphone.label, icon: BUSINESS_CATEGORIES.réparation_téléphone.icon },
  { key: 'restaurant', label: BUSINESS_CATEGORIES.restaurant.label, icon: BUSINESS_CATEGORIES.restaurant.icon },
  { key: 'salle_fêtes', label: BUSINESS_CATEGORIES.salle_fêtes.label, icon: BUSINESS_CATEGORIES.salle_fêtes.icon },
  { key: 'salle_sport', label: BUSINESS_CATEGORIES.salle_sport.label, icon: BUSINESS_CATEGORIES.salle_sport.icon },
  { key: 'sauna', label: BUSINESS_CATEGORIES.sauna.label, icon: BUSINESS_CATEGORIES.sauna.icon },
  { key: 'serrurerie', label: BUSINESS_CATEGORIES.serrurerie.label, icon: BUSINESS_CATEGORIES.serrurerie.icon },
  { key: 'soutien_scolaire', label: BUSINESS_CATEGORIES.soutien_scolaire.label, icon: BUSINESS_CATEGORIES.soutien_scolaire.icon },
  { key: 'spa', label: BUSINESS_CATEGORIES.spa.label, icon: BUSINESS_CATEGORIES.spa.icon },
  { key: 'station_service', label: BUSINESS_CATEGORIES.station_service.label, icon: BUSINESS_CATEGORIES.station_service.icon },
  { key: 'supermarché', label: BUSINESS_CATEGORIES.supermarché.label, icon: BUSINESS_CATEGORIES.supermarché.icon },
  { key: 'tabac_presse', label: BUSINESS_CATEGORIES.tabac_presse.label, icon: BUSINESS_CATEGORIES.tabac_presse.icon },
  { key: 'tatouage', label: BUSINESS_CATEGORIES.tatouage.label, icon: BUSINESS_CATEGORIES.tatouage.icon },
  { key: 'tea', label: BUSINESS_CATEGORIES.tea.label, icon: BUSINESS_CATEGORIES.tea.icon },
  { key: 'téléphonie', label: BUSINESS_CATEGORIES.téléphonie.label, icon: BUSINESS_CATEGORIES.téléphonie.icon },
  { key: 'théâtre', label: BUSINESS_CATEGORIES.théâtre.label, icon: BUSINESS_CATEGORIES.théâtre.icon },
  { key: 'toilettage', label: BUSINESS_CATEGORIES.toilettage.label, icon: BUSINESS_CATEGORIES.toilettage.icon },
  { key: 'traiteur', label: BUSINESS_CATEGORIES.traiteur.label, icon: BUSINESS_CATEGORIES.traiteur.icon },
  { key: 'traiteur_événementiel', label: BUSINESS_CATEGORIES.traiteur_événementiel.label, icon: BUSINESS_CATEGORIES.traiteur_événementiel.icon },
  { key: 'vélo', label: BUSINESS_CATEGORIES.vélo.label, icon: BUSINESS_CATEGORIES.vélo.icon },
  { key: 'vêtements', label: BUSINESS_CATEGORIES.vêtements.label, icon: BUSINESS_CATEGORIES.vêtements.icon },
  { key: 'vêtements_enfant', label: BUSINESS_CATEGORIES.vêtements_enfant.label, icon: BUSINESS_CATEGORIES.vêtements_enfant.icon },
  { key: 'vétérinaire', label: BUSINESS_CATEGORIES.vétérinaire.label, icon: BUSINESS_CATEGORIES.vétérinaire.icon },
  { key: 'yoga', label: BUSINESS_CATEGORIES.yoga.label, icon: BUSINESS_CATEGORIES.yoga.icon }
] as const;

/**
 * Fonction pour obtenir uniquement la clé de catégorie (sans icône) pour l'envoi API
 * Utilisée pour envoyer les données au backend sans les émojis
 */
export const getCategoryKey = (categoryLabelOrKey: string): string => {
  // Si c'est déjà une clé valide, la retourner
  if (BUSINESS_CATEGORIES[categoryLabelOrKey as keyof typeof BUSINESS_CATEGORIES]) {
    return categoryLabelOrKey;
  }

  // Chercher par label complet (ex: "Restaurant")
  const entryByLabel = Object.entries(BUSINESS_CATEGORIES).find(
    ([_, value]) => value.label === categoryLabelOrKey
  );

  if (entryByLabel) {
    return entryByLabel[0];
  }

  // Chercher si c'est une ancienne valeur avec emoji (ex: "🍽️ Restaurant")
  const entryByEmojiLabel = Object.entries(BUSINESS_CATEGORIES).find(
    ([_, value]) => categoryLabelOrKey.includes(value.label)
  );

  if (entryByEmojiLabel) {
    return entryByEmojiLabel[0];
  }

  // Fallback: retourner 'commerce' par défaut
  return 'commerce';
};

/**
 * Fonction pour obtenir le label avec icône pour l'affichage
 */
export const getCategoryDisplay = (categoryKey: string): string => {
  const category = BUSINESS_CATEGORIES[categoryKey as keyof typeof BUSINESS_CATEGORIES];
  if (category) {
    return `${category.icon} ${category.label}`;
  }
  return `${BUSINESS_CATEGORIES.commerce.icon} ${BUSINESS_CATEGORIES.commerce.label}`;
};
